version: '3.8'

services:

  nginx:
    image: nginx:1.17.4-alpine
    ports:
      - 8989:80
    depends_on:
      - php
      - db
    volumes:
      - .:/application
      - ./docker/config/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./docker
    volumes:
      - .:/application
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      - redis
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASS=secret
      - DB_NAME=appquanly

  db:
    image: mariadb:10.5.8
    container_name: db
    ports:
      - "3368:3368"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATEBASE=appquanly
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456

  redis:
    image: redis:5.0.6-alpine
    ports:
      - "6382:6379"
    
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8082:80

volumes:
  db_data: